general{
    hide_cursor= true
    ignore_empty_input= true
}


background {
	monitor = 
	path = screenshot
	blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(213, 125, 219, 0.5)

	placeholder_text = Password?
	fail_text = Try Again.

	outer_color = rgba(E5383Baa) rgba(80797aaa) 200deg
    check_color= rgba(ff6633ee) 
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg


    font_color = rgb(254, 254, 254)
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}

# TO BE INSERTED IN LABELS

# shadow_passes = 1
# shadw_size = 1
# shadow_boost = 5.0
# shadow_color = rgba(6300A9FF)


# time label
label {
    monitor =
	text = cmd[update:1000] echo $TIME12
    font_size = 60
    font_family = $font

    position = 20, -10
    halign = left 
    valign = top
}

# day label
label{
	monitor = 
	text = cmd[update:1000] echo $(date '+%d %B')
	text_align = center
	position = -20, -10
	halign = right
	valign = top
	font_size = 32
}

# year label
label {
	monitor = 
	text = cmd[update:1000] echo $(date '+%Y')
	position = -20, -45
	halign = right
	valign = top
	font_size = 70
	
}
